name: 🔂 Surge PR Preview

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install surge
        run: npm i -g surge
      
      - name: Build Site
        run: npm i && npm run build
      
      - name: Deploy to surge.sh
        run: surge .svelte-kit/build 'flucoma-learn-pr${{ github.event.number }}.surge.sh' --token ${{ secrets.SURGE_TOKEN }}
      